<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="AMITTALE6440" name="scenario.ListnerClass" tests="7" failures="5" timestamp="13 Jul 2017 17:20:15 GMT" time="0.040" errors="0">
  <testcase name="onTestSuccess" time="0.000" classname="scenario.ListnerClass">
    <failure type="org.testng.TestNGException" message="
The data provider is trying to pass 0 parameters but the method scenario.ListnerClass#onTestSuccess takes 1 and TestNG is unable in inject a suitable object">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 0 parameters but the method scenario.ListnerClass#onTestSuccess takes 1 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1313)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1183)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1311)
	... 17 more
]]>
    </failure>
  </testcase> <!-- onTestSuccess -->
  <testcase name="onStart" time="0.002" classname="scenario.ListnerClass"/>
  <testcase name="onFinish" time="0.025" classname="scenario.ListnerClass"/>
  <testcase name="onTestStart" time="0.000" classname="scenario.ListnerClass">
    <failure type="org.testng.TestNGException" message="
The data provider is trying to pass 0 parameters but the method scenario.ListnerClass#onTestStart takes 1 and TestNG is unable in inject a suitable object">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 0 parameters but the method scenario.ListnerClass#onTestStart takes 1 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1313)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1183)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1311)
	... 17 more
]]>
    </failure>
  </testcase> <!-- onTestStart -->
  <testcase name="onTestSkipped" time="0.000" classname="scenario.ListnerClass">
    <failure type="org.testng.TestNGException" message="
The data provider is trying to pass 0 parameters but the method scenario.ListnerClass#onTestSkipped takes 1 and TestNG is unable in inject a suitable object">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 0 parameters but the method scenario.ListnerClass#onTestSkipped takes 1 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1313)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1183)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1311)
	... 17 more
]]>
    </failure>
  </testcase> <!-- onTestSkipped -->
  <testcase name="onTestFailure" time="0.010" classname="scenario.ListnerClass">
    <failure type="org.testng.TestNGException" message="
The data provider is trying to pass 0 parameters but the method scenario.ListnerClass#onTestFailure takes 1 and TestNG is unable in inject a suitable object">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 0 parameters but the method scenario.ListnerClass#onTestFailure takes 1 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1313)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1183)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1311)
	... 17 more
]]>
    </failure>
  </testcase> <!-- onTestFailure -->
  <testcase name="onTestFailedButWithinSuccessPercentage" time="0.003" classname="scenario.ListnerClass">
    <failure type="org.testng.TestNGException" message="
The data provider is trying to pass 0 parameters but the method scenario.ListnerClass#onTestFailedButWithinSuccessPercentage takes 1 and TestNG is unable in inject a suitable object">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 0 parameters but the method scenario.ListnerClass#onTestFailedButWithinSuccessPercentage takes 1 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1313)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1183)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1311)
	... 17 more
]]>
    </failure>
  </testcase> <!-- onTestFailedButWithinSuccessPercentage -->
</testsuite> <!-- scenario.ListnerClass -->
